import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Examples Gallery',
  description: 'Browse GitSkins card, avatar, theme, and README widget examples generated from public GitHub profiles.',
  openGraph: {
    title: 'GitSkins Examples Gallery',
    description: 'See premium GitHub profile cards, avatars, themes, and README widgets generated by GitSkins.',
  },
};

export default function ExamplesLayout({ children }: { children: React.ReactNode }) {
  return children;
}
