/**
 * GitSkins - Site Configuration
 *
 * Centralized configuration for URLs, metadata, and default settings.
 * All environment-dependent values should be defined here.
 */

/**
 * Site metadata and branding
 */
export const siteConfig = {
  /** Site name */
  name: 'GitSkins',
  /** Site description */
  description: 'Generate dynamic, custom-themed SVG widgets for GitHub Profiles',
  /** Site URL (production) */
  url: process.env.NEXT_PUBLIC_SITE_URL || 'https://gitskins.com',
  /** Site domain */
  domain: 'gitskins.com',
  /** Footer text displayed on generated images */
  footerText: 'Generated by GitSkins.com',
} as const;

/**
 * API configuration
 */
export const apiConfig = {
  /** Default theme when none specified */
  defaultTheme: 'github-dark' as const,
  /** Cache duration in seconds (1 hour) */
  cacheMaxAge: 3600,
  /** Shared cache duration in seconds (1 hour) */
  cacheSMaxAge: 3600,
} as const;

/**
 * Image generation constants
 */
export const imageConfig = {
  /** Canvas width in pixels - 2x for better quality */
  width: 1600,
  /** Canvas height in pixels - 2x for better quality */
  height: 800,
  /** Contribution square size in pixels */
  squareSize: 11,
  /** Gap between squares in pixels */
  squareGap: 3,
  /** Graph starting X position */
  graphStartX: 50,
  /** Graph starting Y position */
  graphStartY: 200,
  /** Maximum contributions per day for intensity calculation */
  maxContributionsPerDay: 20,
  /** No-contribution color (grey) */
  noContributionColor: '#161b22',
} as const;

/**
 * GitHub API configuration
 */
export const githubConfig = {
  /** GitHub GraphQL API endpoint */
  apiUrl: 'https://api.github.com/graphql',
  /** Maximum repositories to fetch */
  maxRepositories: 100,
  /** Maximum top languages to display */
  maxTopLanguages: 5,
  /** Rate limit window (seconds) */
  rateLimitWindow: 3600,
} as const;

/**
 * Security headers configuration
 */
export const securityConfig = {
  /** Content Security Policy */
  csp: {
    defaultSrc: ["'self'"],
    imgSrc: ["'self'", 'https:', 'data:'],
    styleSrc: ["'self'", "'unsafe-inline'"],
    scriptSrc: ["'self'", "'unsafe-inline'", "'unsafe-eval'"],
  },
  /** Allowed origins for CORS */
  allowedOrigins: process.env.ALLOWED_ORIGINS
    ? process.env.ALLOWED_ORIGINS.split(',')
    : ['https://gitskins.com', 'https://www.gitskins.com'],
} as const;

/**
 * Rate limiting configuration
 */
export const rateLimitConfig = {
  /** Requests per window (if using KV) */
  requestsPerWindow: 100,
  /** Window duration in seconds */
  windowSeconds: 60,
  /** Enable rate limiting (set to false to disable) */
  enabled: process.env.ENABLE_RATE_LIMITING === 'true',
} as const;

/**
 * Widget dimensions configuration - Higher resolution for better quality
 */
export const widgetConfig = {
  /** Stats widget dimensions */
  stats: { width: 600, height: 240 },
  /** Languages widget dimensions */
  languages: { width: 450, height: 280 },
  /** Streak widget dimensions */
  streak: { width: 600, height: 200 },
  /** Repo card widget dimensions */
  repos: { width: 500, height: 180 },
} as const;
